# -*- coding: utf-8 -*-
import argparse

import __init__


def arg_parse_info():
    """
    Creates command-line arguments
    :return:
    """
    parser = argparse.ArgumentParser(
        prog="Reddit-Deeplearning-Imagetool",
        usage='python reddit_deeplearn_imagetool.py "subreddit1 subreddit2 subredditN" --optional_parameter "SomeValue"',

        description="Checks subreddits, inserts their data into the database and learns.",

        epilog="Please read the Readme.md or contact the maintainer or developers for further information.",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    parser.add_argument("subreddits", metavar='subreddits', type=str,
                        help="The subreddits you want to check.")

    parser.add_argument("-rs", "--reddit_sort", metavar='', type=str,
                        help="The post sorting mechanism (top, rising,..)", default="top")

    parser.add_argument("-rt", "--reddit_time", metavar='', type=str,
                        help="The post time sorting mechanism (hour, day,..)", default="hour")

    parser.add_argument("-c_db", "--create_database", metavar='', type=bool,
                        help="Boolean - create database", default=False)

    parser.add_argument("-db", "--database_path", metavar='', type=str,
                        help="Path to your database", default='AUTOGENERATED.db')

    parser.add_argument("-db_type", "--database_type", metavar='', type=str,
                        help="Type of your database", default='sqlite3')

    parser.add_argument("-db_schema", "--database_schema", metavar='', type=str,
                        help="The database schema - needs to be provided, if you \
                              provide a path to your database.",
                        default="./sql/create.sql")

    parser.add_argument("-v", "--version", action='version', version=__init__.__version__,
                        help="Shows the version number")

    return parser.parse_args()
